apiVersion: v1
kind: ConfigMap
metadata:
  name: portfolio-config
data:
  .env: |     
    NEXT_PUBLIC_NODE_ENV=production
    NEXT_PUBLIC_HELLO=WORLD
    NEXT_PUBLIC_DEV_NAME=VIKRANTH REDDY ALTI
    NEXT_PUBLIC_FAV_FRUIT=PAPAYA
    NEXT_PUBLIC_API_URL=http://localhost:30080
    THEME_COLOR=dark
    NEXT_PUBLIC_FAV_TEAM=Williams, Mercedes, McLaren, Redbull, Ferrari
    SERVER_SIDE_NODE=22
